### ISSUE TITLE
Firefox 85.0.1 causes problem

### ISSUE THREAD

**Issue by Robby-Jo** [GChristensen/scrapyard#32] opened 2021-02-06 23:02 UTC
With Firefox 85.0.1 (64 bit, Windows 10) scrapyard no longer saves websites.

**Comment by GChristensen** [comment] 2021-02-07 07:14
Can not reproduce the problem. The only thing I can suggest is to manually update to the latest Scrapyard version (0.5.2) through the cog menu at the addons settings page without reinstalling the addon. Also, please check, if you are not saving pages from the restricted Mozilla domains: accounts-static.cdn.mozilla.net, accounts.firefox.com, addons.cdn.mozilla.net, addons.mozilla.org, api.accounts.firefox.com,content.cdn.mozilla.net, discovery.addons.mozilla.org, install.mozilla.org, oauth.accounts.firefox.com, profile.accounts.firefox.com, support.mozilla.org, sync.services.mozilla.com.

If the problem persists, I need the debug data, obtained in the following way:

*  Close Firefox
*   Start it again
*   Open a new tab and enter the following URL: about:debugging
*   On this page click "This Firefox" at the top left
*   Find the Scrapyard addon and click "Inspect"
*   On the opened page click the "Console" tab at the top row
*   Try to save a page
*   Post the contents of the console here.

**Comment by Robby-Jo** [comment] 2021-02-07 12:50
> The only thing I can suggest is to manually update to the latest Scrapyard version (0.5.2) through the cog menu at the addons settings page without uninstalling the addon.

Sorry for my ignorance, but what exactly do I have to do for a manual update? When I right-click to open the context menu on the app's settings website, I don't see any option for a manual update of the app. By the way: Where can I see which version of the app is currently installed on my PC?

**Comment by GChristensen** [comment] 2021-02-07 13:51
![addon](https://user-images.githubusercontent.com/170405/107148539-251de500-696d-11eb-973e-4e9015e2409a.png)

**Comment by Robby-Jo** [comment] 2021-02-07 16:45
> Forgot to mention, that it is necessary to do in the Firefox addons settings.

Great support thanks. I already have version 0.5.2 from February 7th.
Error description: After starting an archiving, the usual archiving symbol appears (globe on the crane hook). But the symbol no longer disappears. In the Scrapyard main menu I see that a page has been saved. But if I want to call up this page in the app, Scrapyard reports that no data has been saved. I will now try to provide the debug data.
Thanks for the support.

**Comment by Robby-Jo** [comment] 2021-02-08 09:23
Here is the console debug log ...

![debuginfo](https://user-images.githubusercontent.com/35334161/107200051-7ffc1e80-69f7-11eb-8d24-9f5f72c63e3a.JPG)

**Comment by Robby-Jo** [comment] 2021-02-08 09:34
**And now a second protocol, this time in English ...**

Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). dexie.min.js:2:18912
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. bg.html
Successfully compiled asm.js code (total compilation time 1ms) background.js
Uncaught (in promise) TypeError: tab.sendMessage is not a function
    onopen moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:53
bg.js:53:25
==> background.js loaded background.js:298:9
==> savepage/background.js loaded background.js:1188:9
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    t moz-extension://d47f82b4-cea9-4117-8b80-b4baf922c8a0/data/background.js:8
background.js:8:419
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    r moz-extension://d47f82b4-cea9-4117-8b80-b4baf922c8a0/data/background.js:8
background.js:8:647
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:106
bg.js:106:18
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    reconcileBrowserBookmarksDB moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/backend_browser.js:499
backend_browser.js:499:33
Uncaught (in promise) TypeError: tab.sendMessage is not a function
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:134
bg.js:134:21
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:106
bg.js:106:18
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
==> popup.js loaded popup.js:187:9
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    onload moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:79
    promise callback*window.onload/< moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:72
    withCurrTab moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:12
    promise callback*withCurrTab moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:11
    onload moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:65
    EventHandlerNonNull* moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:29
popup.js:79:26
sendRemoveListener on closed conduit scrapyard-we@firefox.274877907963 ConduitsChild.jsm:108
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
popup.js:164
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:106
bg.js:106:18
The connection to ws://127.0.0.1:59243/ was interrupted while the page was loading. bg.js:46:17
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. backgroundScript.bundle.js:2
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
==> popup.js loaded popup.js:187:9
Promise resolved while context is inactive
popup.js:164
sendRemoveListener on closed conduit scrapyard-we@firefox.274877908232 ConduitsChild.jsm:108
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:106
bg.js:106:18
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://f84ecc6f-dd3b-4545-9703-66ea8d96e4cc/bg.js:106
bg.js:106:18
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’

**Comment by GChristensen** [comment] 2021-02-08 14:37
Does this happens at any time with any page?
The only meaningful error here is:
>Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
>onload moz-extension://804f8ab6-8f65-4528-b8ec-d8df465330ce/popup.js:79
Although it is not critical, but indicates that captured page may be not available entirely online.

**Comment by Robby-Jo** [comment] 2021-02-08 18:46
> Does this happens at any time with any page?
Yes, it has always happened to every web page since Firefox was updated to version 85.0.1. Before that, I had zero problems archiving web pages.
I have now saved my archived websites in a 1 GByte json file. My plan: I uninstall scrapyard, reinstall it and check whether the app then archives web pages again. If it does, I import the data backup and check the function again.
What do you think of it: Good idea or bad idea?

**Comment by GChristensen** [comment] 2021-02-08 19:12
This is the only reasonable option. You also need to restart Firefox between installations.
If this will not help, there are two options, either install version [4.18](https://addons.mozilla.org/firefox/downloads/file/3644119/scrapyard-0.4.18-fx.xpi) because some subtle bugs might have been introduced in the further ones. If this will not help either, I'll make a special debug version, which logs more debug info, because the situation with 1 Gb of saved data seems interesting (there may be a limit on Firefox local storage depending on your free disk space, but since there were no errors, related to the saving process, it is less probable).

**Comment by Robby-Jo** [comment] 2021-02-08 21:03
> WARNING: there is indeed some floating quota. Just tried some stress-testing, my setup handles 2Gb pretty well, but can't import any more after that. Please, do nothing until I figure out what to do with the quota.

All right, I'll be patiently waiting for your results. Take your time, there is no rush :-).

**Comment by GChristensen** [comment] 2021-02-08 21:38
This was a simple bug related to the default 2Gb IndexedDB quota in Firefox. It should be fixed in 0.5.3, please try to update.

**Comment by Robby-Jo** [comment] 2021-02-08 23:30
> This was a simple bug related to the default 2Gb IndexedDB quota in Firefox. It should be fixed in 0.5.3, please try to update without reinstallation, although it may be not related to the situation.

I am very happy and excited. Thanks for your support.

**Comment by Robby-Jo** [comment] 2021-02-08 23:38
> This was a simple bug related to the default 2Gb IndexedDB quota in Firefox. It should be fixed in 0.5.3, please try to update without reinstallation, although it may be not related to the situation.

That was the bug! Scrapyard is now archiving websites again.

**Closed** 2021-02-09 04:34 UTC
