### ISSUE TITLE
Lost whole database again.

### ISSUE THREAD

**Issue by tulipuser** [GChristensen/scrapyard#24] opened 2020-09-20 12:55 UTC
I have no idea why the database is deleted in a regular basis. 

Some day the bookmarked Data is there some days later everything is gone.

And this is the 4 or 5th time scince I use this addon.

**Comment by GChristensen** [comment] 2020-09-20 13:16
How this is manifested. Do you have an empty 'default' shelf or there is only "Loading..." in the list of shelves?

If you open Scrapyard settings, press F12, click on the "Console" in the developer tools window, insert the following code into the bottom line and press ENTER:
```javascript
var _db = indexedDB.open("scrapyard")
_db.onsuccess = function(event) {
  var db = event.target.result;
  var rows_req = db.transaction(["nodes"]).objectStore("nodes").getAll();
  rows_req.onsuccess = function(rows_evt) {
   rows_req.result.map(r => JSON.stringify(r));
   console.log(rows_req.result.map(r => r.name + " ||| " + r.uri).join("\n"));
  }
}
```
you will get contents of your database. Is this set empty?

**Comment by GChristensen** [comment] 2020-09-21 19:51
Since I've got no answer, I close the issue. As it was stated earlier, this is most likely a tree-view issue, if you did not reset your Firefox profile through the "Refresh" option, or manually uninstall and reinstall add-on (in these cases the issue is not related to the add-on at all).
If you are still interested in the issue, please perform a little diagnostic. You need to:

    Close Scraypard sidebar if it is opened
    Close Firefox
    Start it again
    Open a new tab and enter the following URL: about:debugging
    At this page click "This Firefox" at the top left
    Find the Scrapyard addon and click "Inspect"
    On the opened page click the "Console" tab at the top row
    Open Scrapyard sidebar
    Post the contents of the console here.

**Closed by GChristensen** 2020-09-21 19:51 UTC
